[workspace]
members = [
  "./crates/*",
]

[profile.bench]
debug = true

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false